//! This file was automatically generated by "src/scripts/genotype.mjs".
//! Do NOT modify this file manually. Any changes will be overwritten.

export type NETWORK_TYPES = "ethereum";
export const NETWORK_TYPES_ARRAY = ["ethereum"] as const;

export const REGISTRIES = {
  ethereum: async () => await import("../networks/ethereum"),
};

export type NETWORK_CONTRACT_MAP = {
  ethereum: import("../networks/ethereum").ContractConfig;
};

export type DAppUiProps<N extends NETWORK_TYPES = NETWORK_TYPES> = {
  network: N;
  contract: NETWORK_CONTRACT_MAP[N];
};

export type DAppUiContextType = {
  network: NETWORK_TYPES;
  contract: NETWORK_CONTRACT_MAP[NETWORK_TYPES];
};
